# Generated by Django 2.1 on 2018-08-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[(1, 'Mr.'), (2, 'Mrs'), (3, 'Ms')], max_length=100)),
                ('FirstName', models.CharField(default='empty', max_length=200)),
                ('LastName', models.CharField(default='empty', max_length=200)),
                ('Address1', models.CharField(default='empty', max_length=200)),
                ('Address2', models.CharField(default='empty', max_length=200)),
                ('City', models.CharField(default='empty', max_length=200)),
                ('State', models.CharField(choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MP', 'Northern Mariana Islands'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NA', 'National'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin)'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], max_length=100)),
                ('ZipCode', models.IntegerField()),
                ('Telephone', models.CharField(default='empty', max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.URLField()),
                ('Position', models.CharField(default='empty', max_length=200)),
                ('Company', models.CharField(default='empty', max_length=200)),
                ('Meals', models.CharField(choices=[(1, 'MealPack'), (2, 'Day 2 Dinner'), (3, 'D2D')], max_length=100)),
                ('Billing_Firstname', models.CharField(default='empty', max_length=200)),
                ('Billing_Lastname', models.CharField(default='empty', max_length=200)),
                ('Card_Type', models.CharField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'American Express')], max_length=100)),
                ('Card_Number', models.IntegerField()),
                ('Card_CSV', models.IntegerField()),
                ('Exp_Year', models.IntegerField()),
                ('Exp_Month', models.IntegerField()),
                ('Session1', models.CharField(choices=[(1, 'Structuring the Week'), (2, 'Family based Youth ministry'), (3, 'WHY')], max_length=100)),
                ('Session2', models.CharField(choices=[(1, 'The heart of preaching'), (2, 'Running a church summer camp'), (3, 'HOW')], max_length=100)),
                ('Session3', models.CharField(choices=[(1, 'Sermons that are effective'), (2, 'Crises Intervention'), (3, 'Building a culture of evangelism')], max_length=100)),
            ],
        ),
    ]
