# Generated by Django 2.1 on 2018-08-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='empty', max_length=200)),
                ('Session', models.CharField(default='empty', max_length=200)),
                ('Room_Number', models.CharField(default='empty', max_length=200)),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
            ],
        ),
    ]
